# Generated by Django 6.0.5 on 2026-09-30 17:27

import citas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('servicio', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=10)),
                ('dueno', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('token', models.CharField(default=citas.models.generar_token, editable=False, max_length=32, unique=True)),
                ('cliente_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('confirmada', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
