# Generated by Django 6.0.5 on 2026-10-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_iso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
